---
language: java
script: mvn compile package -P full -pl '!subsonic-installer-debian,!subsonic-installer-rpm'

os:
    - linux

jdk:
    - openjdk7

sudo: false
deploy:
  provider: releases
  api_key: "${TRAVIS_TOKEN}"
  file: "subsonic-main/target/subsonic.war"
  skip_cleanup: true
  on:
    tags: true

branches:
    only:
        - release

notifications:
    email:
        - root@cybikbase.com
