---
language: java
script: mvn compile package

os:
    - linux

jdk:
    - openjdk7

sudo: false
deploy:
  provider: releases
  api_key: "97a24589678150ecb68b9a7e83fbd4c35dc14fa6"
  file: "subsonic-main/target/subsonic.war"
  skip_cleanup: true
  on:
    tags: true

branches:
    only:
        - release
notifications:
    email:
        - root@cybikbase.com
